# Generated by Django 6.0.1 on 2026-01-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(upload_to='games/')),
                ('genre', models.CharField(choices=[('action', 'Action'), ('rpg', 'RPG'), ('strategy', 'Strategy'), ('sports', 'Sports'), ('indie', 'Indie')], max_length=50)),
                ('release_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
