# Generated by Django 6.0.1 on 2026-01-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_library_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='min_cpu',
            field=models.CharField(default='Intel Core i5-4460 or AMD Ryzen 3 1200', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='min_gpu',
            field=models.CharField(default='NVIDIA GeForce GTX 960 or AMD Radeon RX 470', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='min_os',
            field=models.CharField(default='Windows 10 64-bit', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='min_ram',
            field=models.CharField(default='8 GB RAM', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='rec_cpu',
            field=models.CharField(default='Intel Core i7-8700 or AMD Ryzen 5 3600', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='rec_gpu',
            field=models.CharField(default='NVIDIA GeForce RTX 2060 or AMD Radeon RX 5700 XT', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='rec_os',
            field=models.CharField(default='Windows 10/11 64-bit', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='rec_ram',
            field=models.CharField(default='16 GB RAM', max_length=200),
        ),
    ]
