# Generated by Django 6.0.1 on 2026-01-13 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_game_min_cpu_game_min_gpu_game_min_os_game_min_ram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='min_cpu',
            field=models.CharField(default='Intel Core i5-4460', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_gpu',
            field=models.CharField(default='NVIDIA GeForce GTX 960', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='rec_cpu',
            field=models.CharField(default='Intel Core i7-8700', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='rec_gpu',
            field=models.CharField(default='NVIDIA GeForce RTX 2060', max_length=200),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.game')),
            ],
            options={
                'unique_together': {('cart', 'game')},
            },
        ),
    ]
